### ISSUE TITLE
Tui theme : open in app

### ISSUE THREAD

**Issue by stagfoo** [stagfoo/tui-website#1]
app will pickup do you just want like host.com/download?theme="bg_color=#999999" and then when you navigate there it downloads automatically, is this sort of what you were thinking?

I already have a normalized so setting it up shouldn't be hard just want to know the best way to get it into the app.

**Comment by fandreuz** [comment]
I was thinking that every theme page there should be a button which copies a unique theme to the clipboard.
Then the users go back to t-ui and use a cmd like "theme -get [url]", and t-ui applies it.
Every url would be ok, but it has to be unique, and also, if you append to it "/theme.xml" or "/suggestions.xml" it must take you to the specific theme.xml/suggestion.xml file of that theme.

I thought we left the idea of creating an url which contains every single option.

**Comment by stagfoo** [comment]
working well
